name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
          go-version-file: './go.mod'
    - name: Build
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v ./...
    - name: Upload a Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build_artifacts
        path: pingpong

  push:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    env: 
      IMAGE_NAME: 'pingpong'

    steps:
      - uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build_artifacts

      - name: Log into github registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push image for github
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          docker build . --file Containerfile --tag $IMAGE_ID:latest
          
          # Push image to GitHub Packages.
          docker push --all-tags $IMAGE_ID
